#
#   Makefile.fpc for GLPaintbox implementation for KCL
#

[targets]
dirs=tests
units=glpaintbox

[require]
toolkit=$(KCLGUI)
packages=fcl x11 opengl gtk

[dirs]
fpcdir=$(KCLDIR)/..
toolkitdir=$(KCLGUIDIR)
componentdir=$(KCLWIDGETSDIR)


[presettings]
# KCL Settings
KCLGUI=kcl_gtk
KCLDIR=../..

KCLGUIDIR=$(KCLDIR)/src
KCLWIDGETSDIR=$(KCLDIR)/widgets


[rules]
.PHONY: tests

tests:
        $(MAKE) tests_all
