#
#   Makefile.fpc for fpGFX X11 target
#

[package]
name=fpgfx_x11
version=1.0.5

[require]
packages=fcl

[target]
units=gfx_x11 gfximpl
rst=gfx_x11

[compiler]
unitdir=.. ../emulayer
options=-S2h

[install]
fpcpackage=y

[default]
fpcdir=../../../../fixbranch
