version: '3'

services:
  identityserver:
      environment:
        - HTTP__BaseURL=http://192.168.1.19:4200/identityserver
        - HTTP__wwwroot=wwwroot
        - HTTP__AllowCorsOrigin=http://localhost:4200

  webclient:
      build:
        args:
          nginxconffile: nginx-default.conf.qa
      ports:
        - "4200:80"

  buildagent_trunk:
      build:
        args:
          inifile: buildagent_docker_x86_64_linux_trunk.ini.prod

  buildagent_304:
      build:
        args:
          inifile: buildagent_docker_x86_64_linux_304.ini.prod

  repository:
      build:
        args:
          inifile: repository_docker.ini.prod

  packagemanager:
      build:
        args:
          inifile: packagemanager_docker.ini.prod

  buildmanager:
      build:
        args:
          inifile: buildmanager_docker.ini.qa

  fppkgrepository:
      build:
        args:
          inifile: fppkgrepository_docker.ini.qa
