version: '3'

services:
  identityserver:
      environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ISSUERURI=http://fpc.cnoc.nl/identityserver
        - WEBCLIENTURI=http://fpc.cnoc.nl

  webclient:
      build:
        args:
          nginxconffile: nginx-default.conf.prod
      ports:
        - "80:80"

  buildagent_trunk:
      build:
        args:
          inifile: buildagent_docker_x86_64_linux_trunk.ini.prod

  buildagent_304:
      build:
        args:
          inifile: buildagent_docker_x86_64_linux_304.ini.prod

  repository:
      build:
        args:
          inifile: repository_docker.ini.prod

  packagemanager:
      build:
        args:
          inifile: packagemanager_docker.ini.prod

  buildmanager:
      build:
        args:
          inifile: buildmanager_docker.ini.prod

  fppkgrepository:
      build:
        args:
          inifile: fppkgrepository_docker.ini.prod
