version: '3'

services:
  identityserver:
      image: 'trunk_identityserver:latest'
      build:
        context: .
        dockerfile: docker-identityserver.dockerfile
      container_name: identityserver

  buildmanager:
      image: 'trunk_buildmanager:latest'
      build:
        context: .
        dockerfile: docker-buildmanager.dockerfile
      depends_on:
        - identityserver
      container_name: buildmanager

  webclient:
      image: 'trunk_webclient:latest'
      build:
        context: .
        dockerfile: docker-webclient.dockerfile
      container_name: webclient
      depends_on:
        - buildagent_trunk
        - buildagent_304
        - identityserver
      volumes:
        - buildfiles:/usr/share/nginx/html/buildfiles
        - repo:/usr/share/nginx/html/repo

  repository:
      image: 'trunk_repository:latest'
      build:
        context: .
        dockerfile: docker-repository.dockerfile
      container_name: repository
      volumes:
        - gitrepos:/home/repository/gitrepos

  packagemanager:
      image: 'trunk_packagemanager:latest'
      build:
        context: .
        dockerfile: docker-packagemanager.dockerfile
      container_name: packagemanager
      volumes:
        - packagedata:/home/packagemanager/data

  buildagent_trunk:
      image: 'trunk_buildagent_trunk:latest'
      build:
        context: .
        dockerfile: docker-buildagent.dockerfile
      container_name: buildagent_trunk
      depends_on:
        - buildmanager
      volumes:
       - buildfiles:/home/buildagent/buildfiles

  buildagent_304:
      image: 'trunk_buildagent_304:latest'
      build:
        context: .
        dockerfile: docker-buildagent.dockerfile
        args:
          - fpcsvn=https://svn.freepascal.org/svn/fpc/tags/release_3_0_4
          - inifile=buildagent_docker_x86_64_linux_304.ini

      container_name: buildagent_304
      depends_on:
        - buildmanager
      volumes:
       - buildfiles:/home/buildagent/buildfiles

  fppkgrepository:
      image: 'trunk_fppkgrepository:latest'
      build:
        context: .
        dockerfile: docker-fppkgrepository.dockerfile
      container_name: fppkgrepository
      depends_on:
        - buildmanager
      volumes:
       - repo:/home/fppkgrepository/repo
       - packagedata:/home/fppkgrepository/data

volumes:
  gitrepos:
  buildfiles:
  repo:
  packagedata:
