version: '3'

services:
  identityserver:
      image: 'quay.io/loesje/identityserver:latest'
      build:
        context: .
        dockerfile: docker-identityserver.dockerfile
      container_name: identityserver
      environment:
        - Credentials__AdminSubjects=M_Joost

  buildmanager:
      image: 'quay.io/loesje/buildmanager:latest'
      build:
        context: .
        dockerfile: docker-buildmanager.dockerfile
      depends_on:
        - identityserver
      container_name: buildmanager

  webclient:
      image: 'quay.io/loesje/webclient:latest'
      build:
        context: .
        dockerfile: docker-webclient.dockerfile
      container_name: webclient
      environment:
        - Buildagent_304_HOST=buildagent_304
        - Buildagent_trunk_HOST=buildagent_trunk
        - Buildagent_fixes32_HOST=buildagent_fixes32
        - Buildagent_320_HOST=buildagent_320
        - Buildmanager_HOST=buildmanager
        - Fppkgrepository_HOST=fppkgrepository
        - Identityserver_HOST=identityserver
        - Packagemanager_HOST=packagemanager
        - Repository_HOST=repository
        - IdentityServerUrl=http://localhost:5000
        - WebClientUrl=http://localhost:4200
        - BuildAgentUrl=http://localhost:8080
        - PackageManagerUrl=http://localhost:8088
        - CategoryUrl=http://localhost:8484
        - BuildManagerUrl=http://localhost:8181
        - RepositoryUrl=http://localhost:8089
        - FppkgRepositoryUrl=http://localhost:8282
        - redirect_https=no
      depends_on:
        - buildagent_trunk
        - buildagent_304
        - buildagent_fixes32
        - buildagent_320
        - identityserver
        - fppkgrepository
        - repository
        - packagemanager
        - buildmanager
      volumes:
        - buildfiles:/usr/share/nginx/html/buildfiles
        - repo:/usr/share/nginx/html/repo

  repository:
      image: 'quay.io/loesje/repository:latest'
      build:
        context: .
        dockerfile: docker-repository.dockerfile
      container_name: repository
      volumes:
        - gitrepos:/home/locuser/gitrepos

  fppkgstack:
      image: 'quay.io/loesje/fppkgstack:latest'
      build:
        context: .
        dockerfile: docker-fppkgstack.dockerfile
      container_name: fppkgstack

  packagemanager:
      image: 'quay.io/loesje/packagemanager:latest'
      build:
        context: .
        dockerfile: docker-packagemanager.dockerfile
      container_name: packagemanager
      volumes:
        - packagedata:/home/locuser/data
      environment:
        - Storage__PackageListFile=/home/locuser/data/packages.json

  category:
      image: 'quay.io/loesje/category:latest'
      build:
        context: .
        dockerfile: docker-category.dockerfile
      container_name: category
      volumes:
        - packagedata:/home/locuser/data
      environment:
        - Storage__CategoryListFile=/home/locuser/data/category.json

  keyword:
      image: 'quay.io/loesje/keyword:latest'
      build:
        context: .
        dockerfile: docker-keyword.dockerfile
      container_name: keyword
      volumes:
        - packagedata:/home/locuser/data
      environment:
        - Storage__KeywordListFile=/home/locuser/data/keyword.json


  buildagent_trunk:
      image: 'quay.io/loesje/buildagent:latest'
      build:
        context: .
        dockerfile: docker-buildagent.dockerfile
      container_name: buildagent_trunk
      depends_on:
        - buildmanager
      volumes:
       - buildfiles:/home/locuser/buildfiles
      environment:
        - TestEnv_x86_64_linux_trunk__FPCSourcePath=/home/locuser/svn/fpc
        - TestEnv_x86_64_linux_trunk__PristineEnvironmentPath=/home/locuser/buildenv/pristine/x86_64-linux-trunk/
        - TestEnv_x86_64_linux_trunk__BuildPath=/home/locuser/buildenv/build/
        - TestEnv_x86_64_linux_trunk__StartCompiler=ppcx64_3.0.4
        - TestEnv_x86_64_linux_trunk__FppkgCfgTemplate=/home/locuser/templates/fppkg.cfg.template
        - TestEnv_x86_64_linux_trunk__RemoteMirrors=http://webclient/repo/testing/mirrors.xml
        - TestEnv_x86_64_linux_trunk__AdditionalPackages=lazmkunit
        - TestEnv_x86_64_linux_trunk__FPCSVNUrl=https://svn.freepascal.org/svn/fpc/trunk

  buildagent_fixes32:
      image: 'quay.io/loesje/buildagent:latest'
      build:
        context: .
        dockerfile: docker-buildagent.dockerfile
      container_name: buildagent_fixes32
      depends_on:
        - buildmanager
      volumes:
       - buildfiles:/home/locuser/buildfiles
      environment:
        - TestEnv_x86_64_linux_fixes32__FPCSourcePath=/home/locuser/svn/fpc
        - TestEnv_x86_64_linux_fixes32__PristineEnvironmentPath=/home/locuser/buildenv/pristine/x86_64-linux-fixes32/
        - TestEnv_x86_64_linux_fixes32__BuildPath=/home/locuser/buildenv/build/
        - TestEnv_x86_64_linux_fixes32__StartCompiler=ppcx64_3.0.2
        - TestEnv_x86_64_linux_fixes32__FppkgCfgTemplate=/home/locuser/templates/fppkg.cfg.template
        - TestEnv_x86_64_linux_fixes32__RemoteMirrors=http://webclient/repo/testing/mirrors.xml
       # - TestEnv_x86_64_linux_fixes32__AdditionalPackages=lazmkunit
        - TestEnv_x86_64_linux_fixes32__FPCSVNUrl=https://svn.freepascal.org/svn/fpc/branches/fixes_3_2

  buildagent_304:
      image: 'quay.io/loesje/buildagent:latest'
      build:
        context: .
        dockerfile: docker-buildagent.dockerfile
      container_name: buildagent_304
      depends_on:
        - buildmanager
      volumes:
       - buildfiles:/home/locuser/buildfiles
      environment:
        - TestEnv_x86_64_linux_3.0.4__FPCSourcePath=/home/locuser/svn/fpc
        - TestEnv_x86_64_linux_3.0.4__PristineEnvironmentPath=/home/locuser/buildenv/pristine/x86_64-linux-3_0_4/
        - TestEnv_x86_64_linux_3.0.4__BuildPath=/home/locuser/buildenv/build/
        - TestEnv_x86_64_linux_3.0.4__StartCompiler=ppcx64_3.0.2
        - TestEnv_x86_64_linux_3.0.4__FppkgCfgTemplate=/home/locuser/templates/fppkg.cfg.304.template
        - TestEnv_x86_64_linux_3.0.4__RemoteMirrors=http://webclient/repo/testing/mirrors.xml
        - TestEnv_x86_64_linux_3.0.4__AdditionalPackages=lazmkunit,fcl-js,fcl-passrc
        - TestEnv_x86_64_linux_3.0.4__AbsoluteFilenamesBug=true
        - TestEnv_x86_64_linux_3.0.4__FPCSVNUrl=https://svn.freepascal.org/svn/fpc/tags/release_3_0_4

  buildagent_320:
    image: 'quay.io/loesje/buildagent:latest'
    build:
      context: .
      dockerfile: docker-buildagent.dockerfile
    container_name: buildagent_320
    depends_on:
      - buildmanager
    volumes:
      - buildfiles:/home/locuser/buildfiles
    environment:
      - TestEnv_x86_64_linux_3.2.0__FPCSourcePath=/home/locuser/svn/fpc
      - TestEnv_x86_64_linux_3.2.0__PristineEnvironmentPath=/home/locuser/buildenv/pristine/x86_64-linux-3_2_0/
      - TestEnv_x86_64_linux_3.2.0__BuildPath=/home/locuser/buildenv/build/
      - TestEnv_x86_64_linux_3.2.0__StartCompiler=ppcx64_3.0.2
      - TestEnv_x86_64_linux_3.2.0__FppkgCfgTemplate=/home/locuser/templates/fppkg.cfg.template
      - TestEnv_x86_64_linux_3.2.0__RemoteMirrors=http://webclient/repo/testing/mirrors.xml
      - TestEnv_x86_64_linux_3.2.0__AdditionalPackages=lazmkunit
      - TestEnv_x86_64_linux_3.2.0__FPCSVNUrl=https://svn.freepascal.org/svn/fpc/tags/release_3_2_0_rc1

  fppkgrepository:
      image: 'quay.io/loesje/fppkgrepository:latest'
      build:
        context: .
        dockerfile: docker-fppkgrepository.dockerfile
      container_name: fppkgrepository
      depends_on:
        - buildmanager
      volumes:
       - repo:/home/locuser/repo
       - packagedata:/home/locuser/data
      environment:
       - Repository_Trunk-Testing__path=/home/locuser/repo/testing
       - Repository_Trunk-Testing__StorageFile=/home/locuser/data/packages-trunk-testing.json
       - Repository_Trunk-Production__path=/home/locuser/repo/prod
       - Repository_Trunk-Production__StorageFile=/home/locuser/data/packages-trunk-production.json
       - Repository_304-Testing__path=/home/locuser/repo/testing
       - Repository_304-Testing__StorageFile=/home/locuser/data/packages-304-testing.json
       - Repository_304-Production__path=/home/locuser/repo/prod
       - Repository_304-Production__StorageFile=/home/locuser/data/packages-304-production.json
       - Repository_fixes32-Testing__path=/home/locuser/repo/testing
       - Repository_fixes32-Testing__StorageFile=/home/locuser/data/packages-fixes32-testing.json
       - Repository_fixes32-Production__path=/home/locuser/repo/prod
       - Repository_fixes32-Production__StorageFile=/home/locuser/data/packages-fixes32-production.json

volumes:
  gitrepos:
  buildfiles:
  repo:
  packagedata:
