version: '3'

services:
  identityserver:
      image: 'fpc.cnoc.nl:5000/identityserver:latest'
      build:
        context: .
        dockerfile: docker-identityserver.dockerfile
      container_name: identityserver

  buildmanager:
      image: 'fpc.cnoc.nl:5000/buildmanager:latest'
      build:
        context: .
        dockerfile: docker-buildmanager.dockerfile
      depends_on:
        - identityserver
      container_name: buildmanager

  webclient:
      image: 'fpc.cnoc.nl:5000/webclient:latest'
      build:
        context: .
        dockerfile: docker-webclient.dockerfile
      container_name: webclient
      depends_on:
        - buildagent_trunk
        - buildagent_304
        - identityserver
        - fppkgrepository
        - repository
        - packagemanager
        - buildmanager
      volumes:
        - buildfiles:/usr/share/nginx/html/buildfiles
        - repo:/usr/share/nginx/html/repo

  repository:
      image: 'fpc.cnoc.nl:5000/repository:latest'
      build:
        context: .
        dockerfile: docker-repository.dockerfile
      container_name: repository
      volumes:
        - gitrepos:/home/locuser/gitrepos

  packagemanager:
      image: 'fpc.cnoc.nl:5000/packagemanager:latest'
      build:
        context: .
        dockerfile: docker-packagemanager.dockerfile
      container_name: packagemanager
      volumes:
        - packagedata:/home/locuser/data

  buildagent_trunk:
      image: 'fpc.cnoc.nl:5000/buildagent:latest'
      build:
        context: .
        dockerfile: docker-buildagent.dockerfile
      container_name: buildagent_trunk
      depends_on:
        - buildmanager
      volumes:
       - buildfiles:/home/locuser/buildfiles
      environment:
        - TestEnv_x86_64_linux_trunk__FPCSourcePath=/home/locuser/svn/fpc
        - TestEnv_x86_64_linux_trunk__PristineEnvironmentPath=/home/locuser/buildenv/pristine/x86_64-linux-trunk/
        - TestEnv_x86_64_linux_trunk__BuildPath=/home/locuser/buildenv/build/
        - TestEnv_x86_64_linux_trunk__StartCompiler=ppcx64_3.0.2
        - TestEnv_x86_64_linux_trunk__FppkgCfgTemplate=/home/locuser/templates/fppkg.cfg.template
        - TestEnv_x86_64_linux_trunk__AdditionalPackages=lazmkunit
        - TestEnv_x86_64_linux_trunk__FPCSVNUrl=https://svn.freepascal.org/svn/fpc/trunk

  buildagent_304:
      image: 'fpc.cnoc.nl:5000/buildagent:latest'
      build:
        context: .
        dockerfile: docker-buildagent.dockerfile
      container_name: buildagent_304
      depends_on:
        - buildmanager
      volumes:
       - buildfiles:/home/locuser/buildfiles
      environment:
        - TestEnv_x86_64_linux_3.0.4__FPCSourcePath=/home/locuser/svn/fpc
        - TestEnv_x86_64_linux_3.0.4__PristineEnvironmentPath=/home/locuser/buildenv/pristine/x86_64-linux-3_0_4/
        - TestEnv_x86_64_linux_3.0.4__BuildPath=/home/locuser/buildenv/build/
        - TestEnv_x86_64_linux_3.0.4__StartCompiler=ppcx64_3.0.2
        - TestEnv_x86_64_linux_3.0.4__FppkgCfgTemplate=/home/locuser/templates/fppkg.cfg.304.template
        - TestEnv_x86_64_linux_3.0.4__AdditionalPackages=lazmkunit,fcl-js,fcl-passrc
        - TestEnv_x86_64_linux_3.0.4__AbsoluteFilenamesBug=true
        - TestEnv_x86_64_linux_3.0.4__FPCSVNUrl=https://svn.freepascal.org/svn/fpc/tags/release_3_0_4

  fppkgrepository:
      image: 'fpc.cnoc.nl:5000/fppkgrepository:latest'
      build:
        context: .
        dockerfile: docker-fppkgrepository.dockerfile
      container_name: fppkgrepository
      depends_on:
        - buildmanager
      volumes:
       - repo:/home/locuser/repo
       - packagedata:/home/locuser/data

volumes:
  gitrepos:
  buildfiles:
  repo:
  packagedata:
