version: '3'

services:
  identityserver:
      environment:
        - HTTP__BaseURL=http://fpc.cnoc.nl/identityserver
        - HTTP__wwwroot=wwwroot

  webclient:
      environment:
        - HOST=fpc.cnoc.nl
      ports:
        - "80:80"

  buildagent_trunk:
      environment:
        - OIDC__OpenIDProviderURL=http://fpc.cnoc.nl/identityserver
        - Connections__BuildManagerURL=http://fpc.cnoc.nl/buildmanager
        - Agent__Name=Default
        - Agent__URL=http://fpc.cnoc.nl/buildagenttrunk/
        - Agent__FPCVersion=trunk
        - BuildFiles__Location=/home/locuser/buildfiles
        - BuildFiles__URL=http://fpc.cnoc.nl/buildfiles/

  buildagent_304:
      environment:
        - OIDC__OpenIDProviderURL=http://fpc.cnoc.nl/identityserver
        - HTTP__Port=9090
        - Connections__BuildManagerURL=http://fpc.cnoc.nl/buildmanager
        - Agent__Name=Default
        - Agent__URL=http://fpc.cnoc.nl/buildagent304/
        - Agent__FPCVersion=3.0.4
        - BuildFiles__Location=/home/locuser/buildfiles
        - BuildFiles__URL=http://fpc.cnoc.nl/buildfiles/

  buildagent_fixes32:
      environment:
        - OIDC__OpenIDProviderURL=http://fpc.cnoc.nl/identityserver
        - HTTP__Port=9091
        - Connections__BuildManagerURL=http://fpc.cnoc.nl/buildmanager
        - Agent__Name=Default
        - Agent__URL=http://fpc.cnoc.nl/buildagentfixes32/
        - Agent__FPCVersion=fixes32
        - BuildFiles__Location=/home/locuser/buildfiles
        - BuildFiles__URL=http://fpc.cnoc.nl/buildfiles/

  repository:
      environment:
       - OIDC__OpenIDProviderURL=http://fpc.cnoc.nl/identityserver
       - Connections__PackageManagerURL=http://packagemanager:8088
       - Connections__BuildManagerURL=http://buildmanager:8181
       - GIT__RepositoriesPath=/home/locuser/gitrepos
       - GIT__UserName=FPPKG Repository server
       - GIT__Email=noreply@cnoc.nl

  packagemanager:
      environment:
       - OIDC__OpenIDProviderURL=http://fpc.cnoc.nl/identityserver

  buildmanager:
      environment:
        - OIDC__OpenIDProviderURL=http://fpc.cnoc.nl/identityserver
        - Connections__PackageManagerURL=http://packagemanager:8088
        - Connections__RepositoryURL=http://repository:8089

  fppkgrepository:
      environment:
        - OIDC__OpenIDProviderURL=http://identityserver:5000
        - Connections__PackageManagerURL=http://packagemanager:8088
        - Connections__RepositoryURL=http://repository:8089
        - Connections__BuildManagerURL=http://buildmanager:8181
        - Repository_Trunk_Testing__BaseURL=http://fpc.cnoc.nl/repo/testing/
        - Repository_Trunk_Production__BaseURL=http://fpc.cnoc.nl/repo/prod/
        - Repository_304_Testing__BaseURL=http://fpc.cnoc.nl/repo/testing/
        - Repository_304_Production__BaseURL=http://fpc.cnoc.nl/repo/prod/
        - Repository_fixes32_Testing__BaseURL=http://fpc.cnoc.nl/repo/testing/
        - Repository_fixes32_Production__BaseURL=http://fpc.cnoc.nl/repo/prod/