version: '3'

services:
  identityserver:
      environment:
        - HTTP__BaseURL=http://fpc.cnoc.nl/identityserver
        - HTTP__wwwroot=wwwroot

  webclient:
      environment:
        - HOST=fpc.cnoc.nl
      ports:
        - "80:80"

  buildagent_trunk:
      build:
        args:
          inifile: buildagent_docker_x86_64_linux_trunk.ini.prod

  buildagent_304:
      build:
        args:
          inifile: buildagent_docker_x86_64_linux_304.ini.prod

  repository:
      environment:
       - OIDC__OpenIDProviderURL=http://fpc.cnoc.nl/identityserver
       - Connections__PackageManagerURL=http://packagemanager:8088
       - Connections__BuildManagerURL=http://buildmanager:8181
       - GIT__RepositoriesPath=/home/locuser/gitrepos
       - GIT__UserName=FPPKG Repository server
       - GIT__Email=noreply@cnoc.nl

  packagemanager:
      environment:
       - OIDC__OpenIDProviderURL=http://fpc.cnoc.nl/identityserver
       - Storage__PackageListFile=/home/locuser/data/packages.json
       - FPCVersion_trunk__Name=trunk
       - FPCVersion_trunk__IsDefault=true
       - FPCVersion_trunk__URLPrefix=3.1.1
       - FPCVersion_304__Name=3.0.4
       - FPCVersion_304__URLPrefix=3.0.4

  buildmanager:
      environment:
        - OIDC__OpenIDProviderURL=http://fpc.cnoc.nl/identityserver
        - Connections__PackageManagerURL=http://packagemanager:8088
        - Connections__RepositoryURL=http://repository:8089

  fppkgrepository:
      build:
        args:
          inifile: fppkgrepository_docker.ini.prod
