version: '3'

services:
  identityserver:
      environment:
        - HTTP__BaseURL=http://172.17.0.1:4200/identityserver
        - HTTP__wwwroot=wwwroot
        - HTTP__AllowCorsOrigin=http://localhost:4200

  webclient:
      environment:
        - HOST=172.17.0.1
      ports:
        - "4200:80"

  buildagent_trunk:
      environment:
        - OIDC__OpenIDProviderURL=http://172.17.0.1:4200/identityserver
        - OIDC__AllowCorsOrigin=http://localhost:4200
        - Connections__BuildManagerURL=http://172.17.0.1:4200/buildmanager
        - Agent__Name=Default
        - Agent__URL=http://172.17.0.1:4200/buildagenttrunk/
        - Agent__FPCVersion=trunk
        - BuildFiles__Location=/home/locuser/buildfiles
        - BuildFiles__URL=http://172.17.0.1:4200/buildfiles/

  buildagent_304:
      environment:
        - OIDC__OpenIDProviderURL=http://172.17.0.1:4200/identityserver
        - OIDC__AllowCorsOrigin=http://localhost:4200
        - HTTP__Port=9090
        - Connections__BuildManagerURL=http://172.17.0.1:4200/buildmanager
        - Agent__Name=Default
        - Agent__URL=http://172.17.0.1:4200/buildagent304/
        - Agent__FPCVersion=3.0.4
        - BuildFiles__Location=/home/locuser/buildfiles
        - BuildFiles__URL=http://172.17.0.1:4200/buildfiles/

  repository:
      environment:
        - OIDC__OpenIDProviderURL=http://172.17.0.1:4200/identityserver
        - HTTP__AllowCorsOrigin=http://localhost:4200
        - Connections__PackageManagerURL=http://172.17.0.1:4200/packagemanager
        - Connections__BuildManagerURL=http://172.17.0.1:4200/buildmanager
        - GIT__RepositoriesPath=/home/locuser/gitrepos
        - GIT__UserName=FPPKG Repository server
        - GIT__Email=noreply@cnoc.nl

  packagemanager:
      environment:
        - OIDC__OpenIDProviderURL=http://identityserver:5000
        - HTTP__AllowCorsOrigin=http://localhost:4200
        - Storage__PackageListFile=/home/locuser/data/packages.json
        - FPCVersion_trunk__Name=trunk
        - FPCVersion_trunk__IsDefault=true
        - FPCVersion_trunk__URLPrefix=3.1.1
        - FPCVersion_304__Name=3.0.4
        - FPCVersion_304__URLPrefix=3.0.4

  buildmanager:
      environment:
        - OIDC__OpenIDProviderURL=http://172.17.0.1:4200/identityserver
        - HTTP__AllowCorsOrigin=http://localhost:4200
        - Connections__PackageManagerURL=http://172.17.0.1:4200/packagemanager
        - Connections__RepositoryURL=http://172.17.0.1:4200/repository

  fppkgrepository:
      environment:
        - OIDC__OpenIDProviderURL=http://identityserver:5000
        - Connections__PackageManagerURL=http://packagemanager:8088
        - Connections__RepositoryURL=http://repository:8089
        - Connections__BuildManagerURL=http://buildmanager:8181
        - Repository_Trunk_Testing__BaseURL=http://172.17.0.1:4200/repo/testing/
        - Repository_Trunk_Production__BaseURL=http://172.17.0.1/repo/prod/
        - Repository_304_Testing__BaseURL=http://172.17.0.1/repo/testing/
        - Repository_304_Production__BaseURL=http://172.17.0.1/repo/prod/
