version: '3'

services:
  identityserver:
      image: 'trunk_identityserver:latest'
      build:
        context: .
        dockerfile: docker-identityserver.dockerfile
      container_name: identityserver

  webclient:
      image: 'trunk_webclient:latest'
      build:
        context: .
        dockerfile: docker-webclient.dockerfile
      container_name: webclient
      depends_on:
        - buildagent
        - identityserver

  buildagent:
      image: 'trunk_buildagent:latest'
      build:
        context: .
        dockerfile: docker-buildagent.dockerfile
      container_name: buildagent

  repository:
      image: 'trunk_repository:latest'
      build:
        context: .
        dockerfile: docker-repository.dockerfile
      container_name: repository

  packagemanager:
      image: 'trunk_packagemanager:latest'
      build:
        context: .
        dockerfile: docker-packagemanager.dockerfile
      container_name: packagemanager
