version: '3'

services:
  identityserver:
      network_mode: "host"
      environment:
        - HTTP__BaseURL=http://localhost:5000
        - HTTP__AllowCorsOrigin=http://localhost:4200
        - HTTP__wwwroot=wwwroot
        - Log_file__Format=console
        - Log_file__Level=Trace

  buildmanager:
      network_mode: "host"
      environment:
        - OIDC__OpenIDProviderURL=http://localhost:5000
        - HTTP__AllowCorsOrigin=http://localhost:4200
        - Connections__PackageManagerURL=http://localhost:8088
        - Connections__RepositoryURL=http://localhost:8089

  fppkgstack:
      network_mode: "host"
      environment:
        - Log_file__Format=console
        - Log_file__Level=Trace

  webclient:
      network_mode: "host"
      environment:
        - HOST=localhost
        - Buildagent_304_HOST=localhost
        - Buildagent_trunk_HOST=localhost
        - Buildagent_fixes32_HOST=localhost
        - Buildmanager_HOST=localhost
        - Fppkgrepository_HOST=localhost
        - Identityserver_HOST=localhost
        - Packagemanager_HOST=localhost
        - Repository_HOST=localhost

  buildagent_trunk:
      network_mode: "host"
      environment:
        - OIDC__OpenIDProviderURL=http://localhost:5000
        - HTTP__AllowCorsOrigin=http://localhost:4200
        - Connections__BuildManagerURL=http://localhost:8181
        - Agent__Name=Default
        - Agent__URL=http://localhost:8080/
        - Agent__FPCVersion=trunk
        - BuildFiles__Location=/home/locuser/buildfiles
        - BuildFiles__URL=http://localhost:4200/buildfiles/

  buildagent_304:
      network_mode: "host"
      environment:
        - OIDC__OpenIDProviderURL=http://localhost:5000
        - HTTP__AllowCorsOrigin=http://localhost:4200
        - HTTP__Port=9090
        - Connections__BuildManagerURL=http://localhost:8181
        - Agent__Name=Default
        - Agent__URL=http://localhost:9090/
        - Agent__FPCVersion=3.0.4
        - BuildFiles__Location=/home/locuser/buildfiles
        - BuildFiles__URL=http://localhost:4200/buildfiles/

  repository:
      network_mode: "host"
      environment:
        - OIDC__OpenIDProviderURL=http://localhost:5000
        - HTTP__AllowCorsOrigin=http://localhost:4200
        - Connections__PackageManagerURL=http://localhost:8088
        - Connections__BuildManagerURL=http://localhost:8181
        - GIT__RepositoriesPath=/home/locuser/gitrepos
        - GIT__UserName=FPPKG Repository server
        - GIT__Email=noreply@cnoc.nl
        - Log_file__Format=console
        - Log_file__Level=Trace

  packagemanager:
      network_mode: "host"
      environment:
        - OIDC__OpenIDProviderURL=http://localhost:5000
        - HTTP__AllowCorsOrigin=http://localhost:4200

  fppkgrepository:
      network_mode: "host"
      environment:
        - OIDC__OpenIDProviderURL=http://localhost:5000
        - Connections__PackageManagerURL=http://localhost:8088
        - Connections__RepositoryURL=http://localhost:8089
        - Connections__BuildManagerURL=http://localhost:8181
        - HTTP__AllowCorsOrigin=http://localhost:4200
        - Repository_Trunk_Testing__BaseURL=http://localhost:4200/repo/testing/
        - Repository_Trunk_Production__BaseURL=http://localhost:4200/repo/prod/
        - Repository_304_Testing__BaseURL=http://localhost:4200/repo/testing/
        - Repository_304_Production__BaseURL=http://localhost:4200/repo/prod/
        - Repository_fixes32_Testing__BaseURL=http://localhost:4200/repo/testing/
        - Repository_fixes32_Production__BaseURL=http://localhost:4200/repo/prod/

  category:
      network_mode: "host"
      environment:
        - OIDC__OpenIDProviderURL=http://localhost:5000
        - HTTP__AllowCorsOrigin=http://localhost:4200
        - Stack__host=localhost
        - Stack__port=5425

  keyword:
      network_mode: "host"
      environment:
        - OIDC__OpenIDProviderURL=http://localhost:5000
        - HTTP__AllowCorsOrigin=http://localhost:4200
        - Stack__host=localhost
        - Stack__port=5425