version: '3'

services:
  identityserver:
      environment:
        - HTTP__BaseURL=http://192.168.1.19:4200/identityserver
        - HTTP__wwwroot=wwwroot
        - HTTP__AllowCorsOrigin=http://localhost:4200

  webclient:
      environment:
        - HOST=192.168.1.19
      ports:
        - "4200:80"

  buildagent_trunk:
      environment:
        - OIDC__OpenIDProviderURL=http://192.168.1.19:4200/identityserver
        - OIDC__AllowCorsOrigin=http://localhost:4200
        - TestEnv_x86_64_linux_trunk__FPCSourcePath=/home/locuser/svn/fpc
        - TestEnv_x86_64_linux_trunk__PristineEnvironmentPath=/home/locuser/buildenv/pristine/x86_64-linux-trunk/
        - TestEnv_x86_64_linux_trunk__BuildPath=/home/locuser/buildenv/build/
        - TestEnv_x86_64_linux_trunk__StartCompiler=ppcx64_3.0.2
        - TestEnv_x86_64_linux_trunk__FppkgCfgTemplate=/home/locuser/templates/fppkg.cfg.template
        - TestEnv_x86_64_linux_trunk__AdditionalPackages=lazmkunit
        - Connections__BuildManagerURL=http://192.168.1.19:4200/buildmanager
        - Agent__Name=Default
        - Agent__URL=http://192.168.1.19:4200/buildagenttrunk/
        - Agent__FPCVersion=trunk
        - BuildFiles__Location=/home/locuser/buildfiles
        - BuildFiles__URL=http://192.168.1.19:4200/buildfiles/

  buildagent_304:
      environment:
        - OIDC__OpenIDProviderURL=http://192.168.1.19:4200/identityserver
        - OIDC__AllowCorsOrigin=http://localhost:4200
        - HTTP__Port=9090
        - TestEnv_x86_64_linux_3.0.4__FPCSourcePath=/home/locuser/svn/fpc
        - TestEnv_x86_64_linux_3.0.4__PristineEnvironmentPath=/home/locuser/buildenv/pristine/x86_64-linux-3_0_4/
        - TestEnv_x86_64_linux_3.0.4__BuildPath=/home/locuser/buildenv/build/
        - TestEnv_x86_64_linux_3.0.4__StartCompiler=ppcx64_3.0.2
        - TestEnv_x86_64_linux_3.0.4__FppkgCfgTemplate=/home/locuser/templates/fppkg.cfg.304.template
        - TestEnv_x86_64_linux_3.0.4__AdditionalPackages=lazmkunit,fcl-js,fcl-passrc
        - TestEnv_x86_64_linux_3.0.4__AbsoluteFilenamesBug=true
        - Connections__BuildManagerURL=http://192.168.1.19:4200/buildmanager
        - Agent__Name=Default
        - Agent__URL=http://192.168.1.19:4200/buildagent304/
        - Agent__FPCVersion=3.0.4
        - BuildFiles__Location=/home/locuser/buildfiles
        - BuildFiles__URL=http://192.168.1.19:4200/buildfiles/

  repository:
      environment:
        - OIDC__OpenIDProviderURL=http://192.168.1.19:4200/identityserver
        - HTTP__AllowCorsOrigin=http://localhost:4200
        - Connections__PackageManagerURL=http://192.168.1.19:4200/packagemanager
        - Connections__BuildManagerURL=http://192.168.1.19:4200/buildmanager
        - GIT__RepositoriesPath=/home/locuser/gitrepos
        - GIT__UserName=FPPKG Repository server
        - GIT__Email=noreply@cnoc.nl

  packagemanager:
      environment:
        - OIDC__OpenIDProviderURL=http://identityserver:5000
        - HTTP__AllowCorsOrigin=http://localhost:4200
        - Storage__PackageListFile=/home/locuser/data/packages.json
        - FPCVersion_trunk__Name=trunk
        - FPCVersion_trunk__IsDefault=true
        - FPCVersion_trunk__URLPrefix=3.1.1
        - FPCVersion_304__Name=3.0.4
        - FPCVersion_304__URLPrefix=3.0.4

  buildmanager:
      environment:
        - OIDC__OpenIDProviderURL=http://192.168.1.19:4200/identityserver
        - HTTP__AllowCorsOrigin=http://localhost:4200
        - Connections__PackageManagerURL=http://192.168.1.19:4200/packagemanager
        - Connections__RepositoryURL=http://192.168.1.19:4200/repository

  fppkgrepository:
      build:
        args:
          inifile: fppkgrepository_docker.ini.qa
