version: '3'

services:
  identityserver:
      environment:
        - HTTP__BaseURL=http://localhost:5000/identityserver
        - HTTP__AllowCorsOrigin=http://localhost:4200
        - HTTP__wwwroot=wwwroot
      ports:
        - "5000:5000"

  buildmanager:
      ports:
        - "8181:8181"

  webclient:
      ports:
        - "4200:80"

  buildagent_trunk:
      ports:
        - "8080:8080"

  buildagent_304:
      ports:
        - "9090:9090"

  repository:
      ports:
        - "8089:8089"

  packagemanager:
      ports:
        - "8088:8088"

  fppkgrepository:
      ports:
        - "8282:8282"
