version: '3'

services:
  identityserver:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
      ports:
        - "5000:5000"

  webclient:
      ports:
        - "4200:80"

  buildagent:
      ports:
        - "8080:8080"

  repository:
      ports:
        - "8089:8089"


  packagemanager:
      ports:
        - "8088:8088"
