version: '3'

services:
  identityserver:
      environment:
        - ASPNETCORE_ENVIRONMENT=Staging
        - ISSUERURI=http://localhost:4200/identityserver

  webclient:
      build:
        args:
          nginxconffile: nginx-default.conf.qa
      ports:
        - "4200:80"

  buildagent:
      build:
        args:
          inifile: buildagent_docker_x86_64_linux_trunk.ini.prod
