version: '3'

services:
  identityserver:
      environment:
        - HTTP__BaseURL=http://192.168.1.19:4200/identityserver
        - HTTP__wwwroot=wwwroot
        - HTTP__AllowCorsOrigin=http://localhost:4200

  webclient:
      environment:
        - HOST=192.168.1.19
      ports:
        - "4200:80"

  buildagent_trunk:
      build:
        args:
          inifile: buildagent_docker_x86_64_linux_trunk.ini.prod

  buildagent_304:
      build:
        args:
          inifile: buildagent_docker_x86_64_linux_304.ini.prod

  repository:
      build:
        args:
          inifile: repository_docker.ini.prod

  packagemanager:
      environment:
       - OIDC__OpenIDProviderURL=http://identityserver:5000
       - HTTP__AllowCorsOrigin=http://localhost:4200
       - Storage__PackageListFile=/home/locuser/data/packages.json
       - FPCVersion_trunk__Name=trunk
       - FPCVersion_trunk__IsDefault=true
       - FPCVersion_trunk__URLPrefix=3.1.1
       - FPCVersion_304__Name=3.0.4
       - FPCVersion_304__URLPrefix=3.0.4

  buildmanager:
      build:
        args:
          inifile: buildmanager_docker.ini.qa

  fppkgrepository:
      build:
        args:
          inifile: fppkgrepository_docker.ini.qa
