version: '3'

services:
  identityserver:
      image: 'fpc.cnoc.nl:5000/identityserver:latest'
      build:
        context: .
        dockerfile: docker-identityserver.dockerfile
      container_name: identityserver

  buildmanager:
      image: 'fpc.cnoc.nl:5000/buildmanager:latest'
      build:
        context: .
        dockerfile: docker-buildmanager.dockerfile
      depends_on:
        - identityserver
      container_name: buildmanager

  webclient:
      image: 'fpc.cnoc.nl:5000/webclient:latest'
      build:
        context: .
        dockerfile: docker-webclient.dockerfile
      container_name: webclient
      depends_on:
        - buildagent_trunk
        - buildagent_304
        - buildagent_fixes32
        - identityserver
        - fppkgrepository
        - repository
        - packagemanager
        - buildmanager
      volumes:
        - buildfiles:/usr/share/nginx/html/buildfiles
        - repo:/usr/share/nginx/html/repo

  repository:
      image: 'fpc.cnoc.nl:5000/repository:latest'
      build:
        context: .
        dockerfile: docker-repository.dockerfile
      container_name: repository
      volumes:
        - gitrepos:/home/locuser/gitrepos

  packagemanager:
      image: 'fpc.cnoc.nl:5000/packagemanager:latest'
      build:
        context: .
        dockerfile: docker-packagemanager.dockerfile
      container_name: packagemanager
      volumes:
        - packagedata:/home/locuser/data

  buildagent_trunk:
      image: 'fpc.cnoc.nl:5000/buildagent:latest'
      build:
        context: .
        dockerfile: docker-buildagent.dockerfile
      container_name: buildagent_trunk
      depends_on:
        - buildmanager
      volumes:
       - buildfiles:/home/locuser/buildfiles
      environment:
        - TestEnv_x86_64_linux_trunk__FPCSourcePath=/home/locuser/svn/fpc
        - TestEnv_x86_64_linux_trunk__PristineEnvironmentPath=/home/locuser/buildenv/pristine/x86_64-linux-trunk/
        - TestEnv_x86_64_linux_trunk__BuildPath=/home/locuser/buildenv/build/
        - TestEnv_x86_64_linux_trunk__StartCompiler=ppcx64_3.0.2
        - TestEnv_x86_64_linux_trunk__FppkgCfgTemplate=/home/locuser/templates/fppkg.cfg.template
        - TestEnv_x86_64_linux_trunk__RemoteMirrors=http://webclient/repo/testing/mirrors.xml
        - TestEnv_x86_64_linux_trunk__AdditionalPackages=lazmkunit
        - TestEnv_x86_64_linux_trunk__FPCSVNUrl=https://svn.freepascal.org/svn/fpc/trunk

  buildagent_fixes32:
      image: 'fpc.cnoc.nl:5000/buildagent:latest'
      build:
        context: .
        dockerfile: docker-buildagent.dockerfile
      container_name: buildagent_fixes32
      depends_on:
        - buildmanager
      volumes:
       - buildfiles:/home/locuser/buildfiles
      environment:
        - TestEnv_x86_64_linux_fixes32__FPCSourcePath=/home/locuser/svn/fpc
        - TestEnv_x86_64_linux_fixes32__PristineEnvironmentPath=/home/locuser/buildenv/pristine/x86_64-linux-fixes32/
        - TestEnv_x86_64_linux_fixes32__BuildPath=/home/locuser/buildenv/build/
        - TestEnv_x86_64_linux_fixes32__StartCompiler=ppcx64_3.0.2
        - TestEnv_x86_64_linux_fixes32__FppkgCfgTemplate=/home/locuser/templates/fppkg.cfg.template
        - TestEnv_x86_64_linux_fixes32__RemoteMirrors=http://webclient/repo/testing/mirrors.xml
       # - TestEnv_x86_64_linux_fixes32__AdditionalPackages=lazmkunit
        - TestEnv_x86_64_linux_fixes32__FPCSVNUrl=https://svn.freepascal.org/svn/fpc/branches/fixes_3_2

  buildagent_304:
      image: 'fpc.cnoc.nl:5000/buildagent:latest'
      build:
        context: .
        dockerfile: docker-buildagent.dockerfile
      container_name: buildagent_304
      depends_on:
        - buildmanager
      volumes:
       - buildfiles:/home/locuser/buildfiles
      environment:
        - TestEnv_x86_64_linux_3.0.4__FPCSourcePath=/home/locuser/svn/fpc
        - TestEnv_x86_64_linux_3.0.4__PristineEnvironmentPath=/home/locuser/buildenv/pristine/x86_64-linux-3_0_4/
        - TestEnv_x86_64_linux_3.0.4__BuildPath=/home/locuser/buildenv/build/
        - TestEnv_x86_64_linux_3.0.4__StartCompiler=ppcx64_3.0.2
        - TestEnv_x86_64_linux_3.0.4__FppkgCfgTemplate=/home/locuser/templates/fppkg.cfg.304.template
        - TestEnv_x86_64_linux_3.0.4__RemoteMirrors=http://webclient/repo/testing/mirrors.xml
        - TestEnv_x86_64_linux_3.0.4__AdditionalPackages=lazmkunit,fcl-js,fcl-passrc
        - TestEnv_x86_64_linux_3.0.4__AbsoluteFilenamesBug=true
        - TestEnv_x86_64_linux_3.0.4__FPCSVNUrl=https://svn.freepascal.org/svn/fpc/tags/release_3_0_4

  fppkgrepository:
      image: 'fpc.cnoc.nl:5000/fppkgrepository:latest'
      build:
        context: .
        dockerfile: docker-fppkgrepository.dockerfile
      container_name: fppkgrepository
      depends_on:
        - buildmanager
      volumes:
       - repo:/home/locuser/repo
       - packagedata:/home/locuser/data
      environment:
       - Repository_Trunk_Testing__Name=Testing
       - Repository_Trunk_Testing__FPCVersion=trunk
       - Repository_Trunk_Testing__NeedAdminRights=False
       - Repository_Trunk_Testing__MasterRepository=Production
       - Repository_Trunk_Testing__path=/home/locuser/repo/testing
       - Repository_Trunk_Testing__BaseURL=http://webclient/repo/testing/
       - Repository_Trunk_Testing__StorageFile=/home/locuser/data/packages-trunk-testing.json
       - Repository_Trunk_Production__Name=Production
       - Repository_Trunk_Production__FPCVersion=trunk
       - Repository_Trunk_Production__NeedAdminRights=True
       - Repository_Trunk_Production__path=/home/locuser/repo/prod
       - Repository_Trunk_Production__BaseURL=http://webclient/repo/prod/
       - Repository_Trunk_Production__StorageFile=/home/locuser/data/packages-trunk-production.json
       - Repository_304_Testing__Name=Testing-304
       - Repository_304_Testing__FPCVersion=3.0.4
       - Repository_304_Testing__NeedAdminRights=False
       - Repository_304_Testing__MasterRepository=Production-304
       - Repository_304_Testing__path=/home/locuser/repo/testing
       - Repository_304_Testing__BaseURL=http://webclient/repo/testing/
       - Repository_304_Testing__Contact=joost@cnoc.nl
       - Repository_304_Testing__StorageFile=/home/locuser/data/packages-304-testing.json
       - Repository_304_Production__Name=Production-304
       - Repository_304_Production__FPCVersion=3.0.4
       - Repository_304_Production__NeedAdminRights=True
       - Repository_304_Production__path=/home/locuser/repo/prod
       - Repository_304_Production__BaseURL=http://webclient/repo/prod/
       - Repository_304_Production__Contact=joost@cnoc.nl
       - Repository_304_Production__StorageFile=/home/locuser/data/packages-304-production.json
       - Repository_fixes32_Testing__Name=Testing-fixes32
       - Repository_fixes32_Testing__FPCVersion=fixes32
       - Repository_fixes32_Testing__NeedAdminRights=False
       - Repository_fixes32_Testing__MasterRepository=Production-fixes32
       - Repository_fixes32_Testing__path=/home/locuser/repo/testing
       - Repository_fixes32_Testing__BaseURL=http://webclient/repo/testing/
       - Repository_fixes32_Testing__Contact=joost@cnoc.nl
       - Repository_fixes32_Testing__StorageFile=/home/locuser/data/packages-fixes32-testing.json
       - Repository_fixes32_Production__Name=Production-fixes32
       - Repository_fixes32_Production__FPCVersion=fixes32
       - Repository_fixes32_Production__NeedAdminRights=True
       - Repository_fixes32_Production__path=/home/locuser/repo/prod
       - Repository_fixes32_Production__BaseURL=http://webclient/repo/prod/
       - Repository_fixes32_Production__Contact=joost@cnoc.nl
       - Repository_fixes32_Production__StorageFile=/home/locuser/data/packages-fixes32-production.json

volumes:
  gitrepos:
  buildfiles:
  repo:
  packagedata:
