version: '3'

services:
  identityserver:
      image: 'fpc.cnoc.nl:5000/identityserver:latest'
      build:
        context: .
        dockerfile: docker-identityserver.dockerfile
      container_name: identityserver

  buildmanager:
      image: 'fpc.cnoc.nl:5000/buildmanager:latest'
      build:
        context: .
        dockerfile: docker-buildmanager.dockerfile
      depends_on:
        - identityserver
      container_name: buildmanager

  webclient:
      image: 'fpc.cnoc.nl:5000/webclient:latest'
      build:
        context: .
        dockerfile: docker-webclient.dockerfile
      container_name: webclient
      depends_on:
        - buildagent_trunk
        - buildagent_304
        - identityserver
        - fppkgrepository
        - repository
        - packagemanager
        - buildmanager
      volumes:
        - buildfiles:/usr/share/nginx/html/buildfiles
        - repo:/usr/share/nginx/html/repo

  repository:
      image: 'fpc.cnoc.nl:5000/repository:latest'
      build:
        context: .
        dockerfile: docker-repository.dockerfile
      container_name: repository
      volumes:
        - gitrepos:/home/locuser/gitrepos

  packagemanager:
      image: 'fpc.cnoc.nl:5000/packagemanager:latest'
      build:
        context: .
        dockerfile: docker-packagemanager.dockerfile
      container_name: packagemanager
      volumes:
        - packagedata:/home/locuser/data

  buildagent_trunk:
      image: 'fpc.cnoc.nl:5000/buildagent_trunk:latest'
      build:
        context: .
        dockerfile: docker-buildagent.dockerfile
      container_name: buildagent_trunk
      depends_on:
        - buildmanager
      volumes:
       - buildfiles:/home/locuser/buildfiles

  buildagent_304:
      image: 'fpc.cnoc.nl:5000/buildagent_304:latest'
      build:
        context: .
        dockerfile: docker-buildagent.dockerfile
        args:
          - fpcsvn=https://svn.freepascal.org/svn/fpc/tags/release_3_0_4
          - inifile=buildagent_docker_x86_64_linux_304.ini

      container_name: buildagent_304
      depends_on:
        - buildmanager
      volumes:
       - buildfiles:/home/locuser/buildfiles

  fppkgrepository:
      image: 'fpc.cnoc.nl:5000/fppkgrepository:latest'
      build:
        context: .
        dockerfile: docker-fppkgrepository.dockerfile
      container_name: fppkgrepository
      depends_on:
        - buildmanager
      volumes:
       - repo:/home/locuser/repo
       - packagedata:/home/locuser/data

volumes:
  gitrepos:
  buildfiles:
  repo:
  packagedata:
