version: '3'

services:
  identityserver:
      build:
        context: .
        dockerfile: docker-identityserver.dockerfile
      container_name: identityserver

  webclient:
      build:
        context: .
        dockerfile: docker-webclient.dockerfile
      container_name: webclient
      depends_on:
        - buildagent
        - identityserver

  buildagent:
      build:
        context: .
        dockerfile: docker-buildagent.dockerfile
      container_name: buildagent


