apiVersion: v1
kind: Service
metadata:
  name: fppkg
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4200
  selector:
    app: fppkg
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fppkg
spec:
  selector:
    matchLabels:
      app: fppkg
  serviceName: "fppkg"
  template:
    metadata:
      name: fppkg
      labels:
        app: fppkg
    spec:
      volumes:
      - name: buildfiles
        persistentVolumeClaim:
          claimName: persistent-disk-buildfiles
      containers:
      # Webclient container
      - name: webclient
        env:
        - name: Buildagent_304_HOST
          value: buildagent-service
        - name: Buildagent_fixes32_HOST
          value: buildagent-service
        - name: Buildagent_trunk_HOST
          value: buildagent-service
        - name: Buildmanager_HOST
          value: localhost
        - name: HOST
          value: fpc.cnoc.nl
        - name: Fppkgrepository_HOST
          value: localhost
        - name: Packagemanager_HOST
          value: localhost
        - name: Identityserver_HOST
          value: localhost
        - name: Repository_HOST
          value: localhost
        image: fppkg.azurecr.io/webclient
        volumeMounts:
        - name: buildfiles
          mountPath: /usr/share/nginx/html/buildfiles
        - name: persistent-disk-repo
          mountPath: /usr/share/nginx/html/repo

      # Identityserver container
      - name: identityserver
        env:
        - name: HTTP__BaseURL
          value: http://51.124.138.35/identityserver
        - name: HTTP__wwwroot
          value: wwwroot
        - name: Log_file__Format
          value: console
        - name: Log_file__Level
          value: Trace
        - name: HTTP__AllowCorsOrigin
          value: http://fpc.cnoc.nl
        image: quay.io/loesje/identityserver

      # Packagemanager container
      - name: packagemanager
        env:
        - name: Storage__PackageListFile
          value: /home/locuser/data/packages.json
        - name: OIDC__OpenIDProviderURL
          value: http://51.124.138.35/identityserver
        image: quay.io/loesje/packagemanager
        volumeMounts:
        - name: persistent-disk-packagedata
          mountPath: /home/locuser/data

      # Buildmanager container
      - name: buildmanager
        env:
        - name: OIDC__OpenIDProviderURL
          value: http://51.124.138.35/identityserver
        - name: Connections__PackageManagerURL
          value: http://localhost:8088
        - name: Connections__RepositoryURL
          value: http://localhost:8089
        image: quay.io/loesje/buildmanager

      # fppkgstack container
      - name: fppkgstack
        env:
        # - name: OIDC__OpenIDProviderURL
        #   value: http://51.124.138.35/identityserver
        - name: Log_file__Format
          value: console
        - name: Log_file__Level
          value: Trace
        image: quay.io/loesje/fppkgstack

      # repository container
      - name: repository
        env:
        - name: OIDC__OpenIDProviderURL
          value: http://51.124.138.35/identityserver
        - name: Log_file__Format
          value: console
        - name: Log_file__Level
          value: Trace
        - name: Connections__PackageManagerURL
          value: http://localhost:8088
        - name: Connections__BuildManagerURL
          value: http://localhost:8181
        - name: GIT__RepositoriesPath
          value: /home/locuser/gitrepos
        - name: GIT__UserName
          value: FPPKG Repository server
        - name: GIT__Email
          value: noreply@cnoc.nl
        image: quay.io/loesje/repository
        volumeMounts:
        - name: persistent-disk-gitrepos
          mountPath: /home/locuser/gitrepos

      # fppkgrepository container
      - name: fppkgrepository
        env:
        - name: OIDC__OpenIDProviderURL
          value: http://51.124.138.35/identityserver

        - name: Log_file__Format
          value: console
        - name: Log_file__Level
          value: Trace

        - name: Connections__PackageManagerURL
          value: http://localhost:8088
        - name: Connections__BuildManagerURL
          value: http://localhost:8181
        - name: Connections__RepositoryURL
          value: http://localhost:8089

        - name: Repository_Trunk-Testing__BaseURL
          value: http://51.124.138.35/repo/testing/
        - name: Repository_Trunk-Testing__path
          value: /home/locuser/repo/testing
        - name: Repository_Trunk-Testing__StorageFile
          value: /home/locuser/data/packages-trunk-testing.json

        - name: Repository_Trunk-Production__BaseURL
          value: http://51.124.138.35/repo/prod/
        - name: Repository_Trunk-Production__path
          value: /home/locuser/repo/prod
        - name: Repository_Trunk-Production__StorageFile
          value: /home/locuser/data/packages-trunk-production.json

        - name: Repository_304-Testing__path
          value: /home/locuser/repo/testing
        - name: Repository_304-Testing__StorageFile
          value: /home/locuser/data/packages-304-testing.json

        - name: Repository_304-Production__path
          value: /home/locuser/repo/prod
        - name: Repository_304-Production__StorageFile
          value: /home/locuser/data/packages-304-production.json

        - name: Repository_fixes32-Testing__path
          value: /home/locuser/repo/testing
        - name: Repository_fixes32-Testing__StorageFile
          value: /home/locuser/data/packages-fixes32-testing.json

        - name: Repository_fixes32-Production__path
          value: /home/locuser/repo/prod
        - name: Repository_fixes32-Production__StorageFile
          value: /home/locuser/data/packages-fixes32-production.json
        image: quay.io/loesje/fppkgrepository
        volumeMounts:
        - name: persistent-disk-repo
          mountPath: /home/locuser/repo
        - name: persistent-disk-packagedata
          mountPath: /home/locuser/data

      # category container
      - name: category
        env:
        - name: OIDC__OpenIDProviderURL
          value: http://51.124.138.35/identityserver
        - name: Log_file__Format
          value: console
        - name: Log_file__Level
          value: Trace
        - name: Storage__CategoryListFile
          value: /home/locuser/data/category.json
        - name: Stack__host
          value: localhost
        - name: Stack__port
          value: "5425"
        image: quay.io/loesje/category
        volumeMounts:
        - name: persistent-disk-packagedata
          mountPath: /home/locuser/data

      # keyword container
      - name: keyword
        env:
        - name: OIDC__OpenIDProviderURL
          value: http://51.124.138.35/identityserver
        - name: Log_file__Format
          value: console
        - name: Log_file__Level
          value: Trace
        - name: Storage__KeywordListFile
          value: /home/locuser/data/keyword.json
        - name: Stack__host
          value: localhost
        - name: Stack__port
          value: "5425"
        image: quay.io/loesje/keyword
        volumeMounts:
        - name: persistent-disk-packagedata
          mountPath: /home/locuser/data
  volumeClaimTemplates:
  - metadata:
      name: persistent-disk-repo
    spec:
      accessModes:
      - ReadWriteMany
      storageClassName: azurefile
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: persistent-disk-packagedata
    spec:
      accessModes:
      - ReadWriteMany
      storageClassName: azurefile
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: persistent-disk-gitrepos
    spec:
      accessModes:
      - ReadWriteMany
      storageClassName: azurefile
      resources:
        requests:
          storage: 1Gi