[package]
name=sdl
version=0.01
# based on most recent release sources in december 2003

[require]
packages=

[target]
dirs=
units= sdl opengl12 sdli386utils sdlutils sdlstreams smpeg sdl_mixer sdl_image sfont

exampledirs=demo2d demo3d

[compiler]
targetdir=basesdl
sourcedir=basesdl 
unitsdir=basesdl
includedir=basesdl include

[install]
basedir=.

[prerules]
sdlutils: sdl
sdli386utils: sdl
sdlstreams: sdl sdlutils

