all:
	latex flexorb
	latex flexorb
pdf:
	pdflatex flexorb
	pdflatex flexorb
	thumbpdf flexorb
	pdflatex flexorb
clean:
	rm -f *.aux *.log *.png *.toc *.out thumb*.*
mrproper:
	rm -f *.aux *.log *.png *.toc *.out thumb*.* *.pdf *.dvi
