#
#   Makefile.fpc for SHEdit implementation for KCL
#

[targets]
units=kclshedit

[require]
packages=fcl

[dirs]
fpcdir=../../..
unitdir=$(KCLGUIDIR)
componentdir=$(KCLWIDGETSDIR)


[presettings]
# KCL Settings
KCLGUI=gtk
KCLDIR=../..

KCLGUIDIR=$(KCLDIR)/src/kcl_$(KCLGUI)
KCLWIDGETSDIR=$(KCLDIR)/widgets
