#
#   Makefile.fpc for SHEdit implementation for KCL
#

[targets]
units=kclshedit

[require]
toolkit=$(KCLGUI)
packages=fcl gtk

[dirs]
fpcdir=$(KCLDIR)/..
toolkitdir=$(KCLGUIDIR)
componentdir=$(KCLWIDGETSDIR)


[presettings]
# KCL Settings
KCLGUI=kcl_gtk
KCLDIR=../..

KCLGUIDIR=$(KCLDIR)/src
KCLWIDGETSDIR=$(KCLDIR)/widgets
