[target]
programs=monofonts_test

[require]
packages=x11 
# sdl

[compiler]
includedir=../../include
unitdir=../../basesdl

[clean]
#units=tictactoe

#[install]
#fpcpackage=y

#[default]
#fpcdir=../../../..

[rules]
monofonts_test: monofonts_test.dpr
	$(COMPILER) monofonts_test.dpr		
