#
#   Makefile.fpc for fpGFX
#

[package]
name=fpgfx
version=0.2

[require]
packages=fcl

[target]
units=gfxbase geldirty gelimage
rsts=gfxbase
dirs_linux=x11
dirs_freebsd=x11
dirs_netbsd=x11
dirs_win32=win32gdi

[compiler]
sourcedir=emulayer
targetdir=.
options=-S2h

[install]
fpcpackage=y
