#
#   Makefile.fpc for GLPaintbox implementation for KCL
#

[targets]
dirs=tests
units=glpaintbox

[require]
packages=fcl x11 opengl

[dirs]
fpcdir=../../..
unitdir=$(KCLGUIDIR)
componentdir=$(KCLWIDGETSDIR)


[presettings]
# KCL Settings
KCLGUI=gtk
KCLDIR=../..

KCLGUIDIR=$(KCLDIR)/src/kcl_$(KCLGUI)
KCLWIDGETSDIR=$(KCLDIR)/widgets


[rules]
.PHONY: tests

tests:
        $(MAKE) tests_all
