#
#   Makefile.fpc for fpGUI
#

[targets]
units=fpgui
dirs=db

[dirs]
incdir=defimpl
#incdir_win32=win32

[require]
options=-S2h
packages=fcl fpgfx

#[libs]
#libname=fpgui

[install]
subdir=

fpcdir=../../../..
