#
#   Makefile.fpc for sizetest
#

[targets]
programs=sizetest


[require]
toolkit=$(KCLGUI)


[dirs]
fpcdir=$(KCLDIR)/..
toolkitdir=$(KCLGUIDIR)


[presettings]
# KCL Settings
KCLGUI=kcl_gtk
KCLDIR=../..

KCLGUIDIR=$(KCLDIR)/src
KCLWIDGETSDIR=$(KCLDIR)/widgets
