#
#   Makefile.fpc for fpGFX
#

[targets]
units=gfxbase
rst=gfxbase
dirs=emulayer
dirs_linux=x11
dirs_win32=win32gdi

[require]
options=-S2h
packages=

[libs]
libname=fpgfx

[install]
subdir=

[dirs]
fpcdir=../../../fpc
