[target]
programs=jedisdlplasma

[require]
packages=x11 
# sdl

[compiler]
includedir=../../include
unitdir=../../basesdl

[clean]
#units=tictactoe

#[install]
#fpcpackage=y

#[default]
#fpcdir=../../../..

[rules]
jedisdlplasma: jedisdlplasma.dpr
	$(COMPILER) jedisdlplasma.dpr		
