[target]
programs=oxygene

[require]
packages=x11 
# sdl

[compiler]
includedir=../../include
unitdir=../../basesdl

[clean]
#units=tictactoe

#[install]
#fpcpackage=y

#[default]
#fpcdir=../../../..

[rules]
oxygene: oxygene.dpr
	$(COMPILER) oxygene.dpr		
