all:
	latex kcl
	latex kcl
pdf:
	pdflatex kcl
	pdflatex kcl
	thumbpdf kcl
	pdflatex kcl
clean:
	rm -f *.aux *.log *.png *.toc *.out thumb*.*
mrproper:
	rm -f *.aux *.log *.png *.toc *.out thumb*.* *.pdf *.dvi
