[target]
programs=jedisdlmouse

[require]
packages=x11 
# sdl

[compiler]
includedir=../../include
unitdir=../../basesdl

[clean]
#units=tictactoe

#[install]
#fpcpackage=y

#[default]
#fpcdir=../../../..

[rules]
jedisdlmouse: jedisdlmouse.dpr
	$(COMPILER) jedisdlmouse.dpr		
