#
#   Makefile.fpc for Kassandra
#

[targets]
units=viewman vw_shtext
programs=kassandra
rst=kassandra


[require]
packages=fcl x11
components=kclshedit


[dirs]
fpcdir=../../../..
unitdir=$(KCLGUIDIR)
componentdir=$(KCLWIDGETSDIR)


[presettings]
# KCL Settings
KCLGUI=gtk
KCLDIR=../../..

KCLGUIDIR=$(KCLDIR)/src/kcl_$(KCLGUI)
KCLWIDGETSDIR=$(KCLDIR)/widgets
