[target]
programs=jedisdlblockout

[require]
packages=x11 
# sdl

[compiler]
includedir=../../include
unitdir=../../basesdl

[clean]
#units=tictactoe

#[install]
#fpcpackage=y

#[default]
#fpcdir=../../../..

[rules]
jedisdlblockout: jedisdlblockout.dpr
	$(COMPILER) jedisdlblockout.dpr		
