#
#   Makefile.fpc for Kassandra
#

[targets]
units=viewman vw_shtext
programs=kassandra
rst=kassandra


[require]
toolkit=$(KCLGUI)
packages=fcl gtk
components=kclshedit


[dirs]
fpcdir=$(KCLDIR)/..
toolkitdir=$(KCLGUIDIR)
componentdir=$(KCLWIDGETSDIR)


[presettings]
# KCL Settings
KCLGUI=kcl_gtk
KCLDIR=../../..

KCLGUIDIR=$(KCLDIR)/src
KCLWIDGETSDIR=$(KCLDIR)/widgets
