#
#   Makefile.fpc for KCL GTK Implementation
#

[targets]
units=kcl
rst=kcl

[require]
packages=fcl gtk

[install]
subdir=kcl

[dirs]
fpcdir=../../..
incdir=../inc ../common


[rules]
kcl$(PPUEXT): $(wildcard *.inc) $(wildcard ../inc/*.inc) kcl.pp
