@echo off
del longlog.log
call docomp.bat  jwaaccctrl.pp
call docomp.bat  jwaaclapi.pp
call docomp.bat  jwaaclui.pp
call docomp.bat  jwaactiveds.pp
call docomp.bat  jwaadsdb.pp
call docomp.bat  jwaadserr.pp
call docomp.bat  jwaadshlp.pp
call docomp.bat  jwaadsnms.pp
call docomp.bat  jwaadsprop.pp
call docomp.bat  jwaadssts.pp
call docomp.bat  jwaadstlb.pp
call docomp.bat  jwaadtgen.pp
call docomp.bat  jwaaf_irda.pp
call docomp.bat  jwaatalkwsh.pp
call docomp.bat  jwaauthif.pp
call docomp.bat  jwaauthz.pp
call docomp.bat  jwabatclass.pp
call docomp.bat  jwabits.pp
call docomp.bat  jwabitsmsg.pp
call docomp.bat  jwablberr.pp
call docomp.bat  jwabugcodes.pp
call docomp.bat  jwacderr.pp
call docomp.bat  jwacmnquery.pp
call docomp.bat  jwacolordlg.pp
call docomp.bat  jwacpl.pp
call docomp.bat  jwacplext.pp
call docomp.bat  jwacryptuiapi.pp
call docomp.bat  jwadbt.pp
call docomp.bat  jwadde.pp
call docomp.bat  jwadhcpcsdk.pp
call docomp.bat  jwadhcpssdk.pp
call docomp.bat  jwadlgs.pp
call docomp.bat  jwadsadmin.pp
call docomp.bat  jwadsclient.pp
call docomp.bat  jwadsgetdc.pp
call docomp.bat  jwadskquota.pp
call docomp.bat  jwadsquery.pp
call docomp.bat  jwadsrole.pp
call docomp.bat  jwaerrorrep.pp
call docomp.bat  jwaexcpt.pp
call docomp.bat  jwafaxdev.pp
call docomp.bat  jwafaxext.pp
call docomp.bat  jwafaxmmc.pp
call docomp.bat  jwafaxroute.pp
call docomp.bat  jwagpedit.pp
call docomp.bat  jwahherror.pp
call docomp.bat  jwahtmlguid.pp
call docomp.bat  jwahtmlhelp.pp
call docomp.bat  jwaiaccess.pp
call docomp.bat  jwaiadmext.pp
call docomp.bat  jwaiiscnfg.pp
call docomp.bat  jwaimagehlp.pp
call docomp.bat  jwaimapi.pp
call docomp.bat  jwaimapierror.pp
call docomp.bat  jwaime.pp
call docomp.bat  jwaioevent.pp
call docomp.bat  jwaipexport.pp
call docomp.bat  jwaiphlpapi.pp
call docomp.bat  jwaipifcons.pp
call docomp.bat  jwaipinfoid.pp
call docomp.bat  jwaiprtrmib.pp
call docomp.bat  jwaiptypes.pp
call docomp.bat  jwaisguids.pp
call docomp.bat  jwaissper16.pp
call docomp.bat  jwalm.pp
call docomp.bat  jwalmaccess.pp
call docomp.bat  jwalmalert.pp
call docomp.bat  jwalmapibuf.pp
call docomp.bat  jwalmat.pp
call docomp.bat  jwalmaudit.pp
call docomp.bat  jwalmconfig.pp
call docomp.bat  jwalmcons.pp
call docomp.bat  jwalmdfs.pp
call docomp.bat  jwalmerr.pp
call docomp.bat  jwalmerrlog.pp
call docomp.bat  jwalmjoin.pp
call docomp.bat  jwalmmsg.pp
call docomp.bat  jwalmremutl.pp
call docomp.bat  jwalmrepl.pp
call docomp.bat  jwalmserver.pp
call docomp.bat  jwalmshare.pp
call docomp.bat  jwalmsname.pp
call docomp.bat  jwalmstats.pp
call docomp.bat  jwalmsvc.pp
call docomp.bat  jwalmuse.pp
call docomp.bat  jwalmuseflg.pp
call docomp.bat  jwalmwksta.pp
call docomp.bat  jwaloadperf.pp
call docomp.bat  jwalpmapi.pp
call docomp.bat  jwamciavi.pp
call docomp.bat  jwamprerror.pp
call docomp.bat  jwamsi.pp
call docomp.bat  jwamsidefs.pp
call docomp.bat  jwamsiquery.pp
call docomp.bat  jwamstask.pp
call docomp.bat  jwamstcpip.pp
call docomp.bat  jwamswsock.pp
call docomp.bat  jwanb30.pp
call docomp.bat  jwanetsh.pp
call docomp.bat  jwanspapi.pp
call docomp.bat  jwantdsapi.pp
call docomp.bat  jwantdsbcli.pp
call docomp.bat  jwantdsbmsg.pp
call docomp.bat  jwantldap.pp
call docomp.bat  jwantquery.pp
call docomp.bat  jwantsecapi.pp
call docomp.bat  jwantstatus.pp
call docomp.bat  jwaobjsel.pp
call docomp.bat  jwapatchapi.pp
call docomp.bat  jwapatchwiz.pp
call docomp.bat  jwapbt.pp
call docomp.bat  jwapdh.pp
call docomp.bat  jwapdhmsg.pp
call docomp.bat  jwapowrprof.pp
call docomp.bat  jwaprofinfo.pp
call docomp.bat  jwaprotocol.pp
call docomp.bat  jwaprsht.pp
call docomp.bat  jwapsapi.pp
call docomp.bat  jwaqos.pp
call docomp.bat  jwaqosname.pp
call docomp.bat  jwaqospol.pp
call docomp.bat  jwaqossp.pp
call docomp.bat  jwareason.pp
call docomp.bat  jwaregstr.pp
call docomp.bat  jwarpc.pp
call docomp.bat  jwarpcasync.pp
call docomp.bat  jwarpcdce.pp
call docomp.bat  jwarpcnsi.pp
call docomp.bat  jwarpcnterr.pp
call docomp.bat  jwarpcssl.pp
call docomp.bat  jwascesvc.pp
call docomp.bat  jwaschedule.pp
call docomp.bat  jwaschemadef.pp
call docomp.bat  jwasddl.pp
call docomp.bat  jwasecext.pp
call docomp.bat  jwasecurity.pp
call docomp.bat  jwasens.pp
call docomp.bat  jwasensapi.pp
call docomp.bat  jwasensevts.pp
call docomp.bat  jwasfc.pp
call docomp.bat  jwashlguid.pp
call docomp.bat  jwasisbkup.pp
call docomp.bat  jwasnmp.pp
call docomp.bat  jwasporder.pp
call docomp.bat  jwasrrestoreptapi.pp
call docomp.bat  jwasspi.pp
call docomp.bat  jwasubauth.pp
call docomp.bat  jwasvcguid.pp
call docomp.bat  jwatlhelp32.pp
call docomp.bat  jwatmschema.pp
call docomp.bat  jwatraffic.pp
call docomp.bat  jwauserenv.pp
call docomp.bat  jwauxtheme.pp
call docomp.bat  jwawbemcli.pp
call docomp.bat  jwawinable.pp
call docomp.bat  jwawinbase.pp
call docomp.bat  jwawinber.pp
call docomp.bat  jwawincon.pp
call docomp.bat  jwawincpl.pp
call docomp.bat  jwawincred.pp
call docomp.bat  jwawincrypt.pp
call docomp.bat  jwawindns.pp
call docomp.bat  jwawinefs.pp
call docomp.bat  jwawinerror.pp
call docomp.bat  jwawinfax.pp
call docomp.bat  jwawingdi.pp
call docomp.bat  jwawinioctl.pp
call docomp.bat  jwawinldap.pp
call docomp.bat  jwawinnetwk.pp
call docomp.bat  jwawinnls.pp
call docomp.bat  jwawinnt.pp
call docomp.bat  jwawinperf.pp
call docomp.bat  jwawinreg.pp
call docomp.bat  jwawinsafer.pp
call docomp.bat  jwawinsock.pp
call docomp.bat  jwawinsock2.pp
call docomp.bat  jwawinsvc.pp
call docomp.bat  jwawintype.pp
call docomp.bat  jwawinuser.pp
call docomp.bat  jwawinver.pp
call docomp.bat  jwawinwlx.pp
call docomp.bat  jwawmistr.pp
call docomp.bat  jwawownt16.pp
call docomp.bat  jwawownt32.pp
call docomp.bat  jwawpapi.pp
call docomp.bat  jwawpapimsg.pp
call docomp.bat  jwawpcrsmsg.pp
call docomp.bat  jwawpftpmsg.pp
call docomp.bat  jwawppstmsg.pp
call docomp.bat  jwawpspihlp.pp
call docomp.bat  jwawptypes.pp
call docomp.bat  jwawpwizmsg.pp
call docomp.bat  jwaws2atm.pp
call docomp.bat  jwaws2dnet.pp
call docomp.bat  jwaws2spi.pp
call docomp.bat  jwaws2tcpip.pp
call docomp.bat  jwawshisotp.pp
call docomp.bat  jwawsipx.pp
call docomp.bat  jwawsnetbs.pp
call docomp.bat  jwawsnwlink.pp
call docomp.bat  jwawsvns.pp
call docomp.bat  jwawtsapi32.pp
call docomp.bat  jwazmouse.pp
