@echo off
del longlog.log
call docomp2.bat jwaaccctrl.pp
call docomp2.bat  jwaaclapi.pp
call docomp2.bat  jwaaclui.pp
call docomp2.bat  jwaactiveds.pp
call docomp2.bat  jwaadsdb.pp
call docomp2.bat  jwaadserr.pp
call docomp2.bat  jwaadshlp.pp
call docomp2.bat  jwaadsnms.pp
call docomp2.bat  jwaadsprop.pp
call docomp2.bat  jwaadssts.pp
call docomp2.bat  jwaadstlb.pp
call docomp2.bat  jwaadtgen.pp
call docomp2.bat  jwaaf_irda.pp
call docomp2.bat  jwaatalkwsh.pp
call docomp2.bat  jwaauthif.pp
call docomp2.bat  jwaauthz.pp
call docomp2.bat  jwabatclass.pp
call docomp2.bat  jwabits.pp
call docomp2.bat  jwabitsmsg.pp
call docomp2.bat  jwablberr.pp
call docomp2.bat  jwabugcodes.pp
call docomp2.bat  jwacderr.pp
call docomp2.bat  jwacmnquery.pp
call docomp2.bat  jwacolordlg.pp
call docomp2.bat  jwacpl.pp
call docomp2.bat  jwacplext.pp
call docomp2.bat  jwacryptuiapi.pp
call docomp2.bat  jwadbt.pp
call docomp2.bat  jwadde.pp
call docomp2.bat  jwadhcpcsdk.pp
call docomp2.bat  jwadhcpssdk.pp
call docomp2.bat  jwadlgs.pp
call docomp2.bat  jwadsadmin.pp
call docomp2.bat  jwadsclient.pp
call docomp2.bat  jwadsgetdc.pp
call docomp2.bat  jwadskquota.pp
call docomp2.bat  jwadsquery.pp
call docomp2.bat  jwadsrole.pp
call docomp2.bat  jwaerrorrep.pp
call docomp2.bat  jwaexcpt.pp
call docomp2.bat  jwafaxdev.pp
call docomp2.bat  jwafaxext.pp
call docomp2.bat  jwafaxmmc.pp
call docomp2.bat  jwafaxroute.pp
call docomp2.bat  jwagpedit.pp
call docomp2.bat  jwahherror.pp
call docomp2.bat  jwahtmlguid.pp
call docomp2.bat  jwahtmlhelp.pp
call docomp2.bat  jwaiaccess.pp
call docomp2.bat  jwaiadmext.pp
call docomp2.bat  jwaiiscnfg.pp
call docomp2.bat  jwaimagehlp.pp
call docomp2.bat  jwaimapi.pp
call docomp2.bat  jwaimapierror.pp
call docomp2.bat  jwaime.pp
call docomp2.bat  jwaioevent.pp
call docomp2.bat  jwaipexport.pp
call docomp2.bat  jwaiphlpapi.pp
call docomp2.bat  jwaipifcons.pp
call docomp2.bat  jwaipinfoid.pp
call docomp2.bat  jwaiprtrmib.pp
call docomp2.bat  jwaiptypes.pp
call docomp2.bat  jwaisguids.pp
call docomp2.bat  jwaissper16.pp
call docomp2.bat  jwalm.pp
call docomp2.bat  jwalmaccess.pp
call docomp2.bat  jwalmalert.pp
call docomp2.bat  jwalmapibuf.pp
call docomp2.bat  jwalmat.pp
call docomp2.bat  jwalmaudit.pp
call docomp2.bat  jwalmconfig.pp
call docomp2.bat  jwalmcons.pp
call docomp2.bat  jwalmdfs.pp
call docomp2.bat  jwalmerr.pp
call docomp2.bat  jwalmerrlog.pp
call docomp2.bat  jwalmjoin.pp
call docomp2.bat  jwalmmsg.pp
call docomp2.bat  jwalmremutl.pp
call docomp2.bat  jwalmrepl.pp
call docomp2.bat  jwalmserver.pp
call docomp2.bat  jwalmshare.pp
call docomp2.bat  jwalmsname.pp
call docomp2.bat  jwalmstats.pp
call docomp2.bat  jwalmsvc.pp
call docomp2.bat  jwalmuse.pp
call docomp2.bat  jwalmuseflg.pp
call docomp2.bat  jwalmwksta.pp
call docomp2.bat  jwaloadperf.pp
call docomp2.bat  jwalpmapi.pp
call docomp2.bat  jwamciavi.pp
call docomp2.bat  jwamprerror.pp
call docomp2.bat  jwamsi.pp
call docomp2.bat  jwamsidefs.pp
call docomp2.bat  jwamsiquery.pp
call docomp2.bat  jwamstask.pp
call docomp2.bat  jwamstcpip.pp
call docomp2.bat  jwamswsock.pp
call docomp2.bat  jwanb30.pp
call docomp2.bat  jwanetsh.pp
call docomp2.bat  jwanspapi.pp
call docomp2.bat  jwantdsapi.pp
call docomp2.bat  jwantdsbcli.pp
call docomp2.bat  jwantdsbmsg.pp
call docomp2.bat  jwantldap.pp
call docomp2.bat  jwantquery.pp
call docomp2.bat  jwantsecapi.pp
call docomp2.bat  jwantstatus.pp
call docomp2.bat  jwaobjsel.pp
call docomp2.bat  jwapatchapi.pp
call docomp2.bat  jwapatchwiz.pp
call docomp2.bat  jwapbt.pp
call docomp2.bat  jwapdh.pp
call docomp2.bat  jwapdhmsg.pp
call docomp2.bat  jwapowrprof.pp
call docomp2.bat  jwaprofinfo.pp
call docomp2.bat  jwaprotocol.pp
call docomp2.bat  jwaprsht.pp
call docomp2.bat  jwapsapi.pp
call docomp2.bat  jwaqos.pp
call docomp2.bat  jwaqosname.pp
call docomp2.bat  jwaqospol.pp
call docomp2.bat  jwaqossp.pp
call docomp2.bat  jwareason.pp
call docomp2.bat  jwaregstr.pp
call docomp2.bat  jwarpc.pp
call docomp2.bat  jwarpcasync.pp
call docomp2.bat  jwarpcdce.pp
call docomp2.bat  jwarpcnsi.pp
call docomp2.bat  jwarpcnterr.pp
call docomp2.bat  jwarpcssl.pp
call docomp2.bat  jwascesvc.pp
call docomp2.bat  jwaschedule.pp
call docomp2.bat  jwaschemadef.pp
call docomp2.bat  jwasddl.pp
call docomp2.bat  jwasecext.pp
call docomp2.bat  jwasecurity.pp
call docomp2.bat  jwasens.pp
call docomp2.bat  jwasensapi.pp
call docomp2.bat  jwasensevts.pp
call docomp2.bat  jwasfc.pp
call docomp2.bat  jwashlguid.pp
call docomp2.bat  jwasisbkup.pp
call docomp2.bat  jwasnmp.pp
call docomp2.bat  jwasporder.pp
call docomp2.bat  jwasrrestoreptapi.pp
call docomp2.bat  jwasspi.pp
call docomp2.bat  jwasubauth.pp
call docomp2.bat  jwasvcguid.pp
call docomp2.bat  jwatlhelp32.pp
call docomp2.bat  jwatmschema.pp
call docomp2.bat  jwatraffic.pp
call docomp2.bat  jwauserenv.pp
call docomp2.bat  jwauxtheme.pp
call docomp2.bat  jwawbemcli.pp
call docomp2.bat  jwawinable.pp
call docomp2.bat  jwawinbase.pp
call docomp2.bat  jwawinber.pp
call docomp2.bat  jwawincon.pp
call docomp2.bat  jwawincpl.pp
call docomp2.bat  jwawincred.pp
call docomp2.bat  jwawincrypt.pp
call docomp2.bat  jwawindns.pp
call docomp2.bat  jwawinefs.pp
call docomp2.bat  jwawinerror.pp
call docomp2.bat  jwawinfax.pp
call docomp2.bat  jwawingdi.pp
call docomp2.bat  jwawinioctl.pp
call docomp2.bat  jwawinldap.pp
call docomp2.bat  jwawinnetwk.pp
call docomp2.bat  jwawinnls.pp
call docomp2.bat  jwawinnt.pp
call docomp2.bat  jwawinperf.pp
call docomp2.bat  jwawinreg.pp
call docomp2.bat  jwawinsafer.pp
call docomp2.bat  jwawinsock.pp
call docomp2.bat  jwawinsock2.pp
call docomp2.bat  jwawinsvc.pp
call docomp2.bat  jwawintype.pp
call docomp2.bat  jwawinuser.pp
call docomp2.bat  jwawinver.pp
call docomp2.bat  jwawinwlx.pp
call docomp2.bat  jwawmistr.pp
call docomp2.bat  jwawownt16.pp
call docomp2.bat  jwawownt32.pp
call docomp2.bat  jwawpapi.pp
call docomp2.bat  jwawpapimsg.pp
call docomp2.bat  jwawpcrsmsg.pp
call docomp2.bat  jwawpftpmsg.pp
call docomp2.bat  jwawppstmsg.pp
call docomp2.bat  jwawpspihlp.pp
call docomp2.bat  jwawptypes.pp
call docomp2.bat  jwawpwizmsg.pp
call docomp2.bat  jwaws2atm.pp
call docomp2.bat  jwaws2dnet.pp
call docomp2.bat  jwaws2spi.pp
call docomp2.bat  jwaws2tcpip.pp
call docomp2.bat  jwawshisotp.pp
call docomp2.bat  jwawsipx.pp
call docomp2.bat  jwawsnetbs.pp
call docomp2.bat  jwawsnwlink.pp
call docomp2.bat  jwawsvns.pp
call docomp2.bat  jwawtsapi32.pp
call docomp2.bat  jwazmouse.pp
