#
#   Makefile.fpc for GLPaintbox Demo for KCL
#

[targets]
programs=ogldemo1 ogldemo2


[require]
toolkit=$(KCLGUI)
packages=fcl x11 opengl
components=glpaintbox

[dirs]
fpcdir=$(KCLDIR)/..
toolkitdir=$(KCLGUIDIR)
componentdir=$(KCLWIDGETSDIR)


[presettings]
# KCL Settings
KCLGUI=kcl_gtk
KCLDIR=../../..

KCLGUIDIR=$(KCLDIR)/src
KCLWIDGETSDIR=$(KCLDIR)/widgets


[rules]
.PHONY: tests

tests:
        $(MAKE) tests_all
