#
#   Makefile.fpc for GLPaintbox Demo for KCL
#

[targets]
programs=ogldemo1 ogldemo2


[require]
packages=x11 opengl
components=glpaintbox


[dirs]
fpcdir=../../../..
unitdir=$(KCLGUIDIR)
componentdir=$(KCLWIDGETSDIR)


[presettings]
# KCL Settings
KCLGUI=gtk
KCLDIR=../../..

KCLGUIDIR=$(KCLDIR)/src/kcl_$(KCLGUI)
KCLWIDGETSDIR=$(KCLDIR)/widgets


[rules]
.PHONY: tests

tests:
        $(MAKE) tests_all
