
[target]
programs_win32=concli2 conftp conhttp consmtp consrv1
srcexT=($SRCEXT

[require]
#packages=fcl

[compiler]
#options=-S2
includedir=../vc32
unitdir=../vc32

[install]
fpcpackage=y

[default]
#fpcdir=../..


#[rules]


#concli2($EXEEXT): concli2.dpr
#conftp($EXEEXT): conftp.dpr




